AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for container-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  BestModel:
    Type: String
    Default: ModelBest.pkl

Resources:
  ImplicitGetProductsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 300
      MemorySize: 2048  
      Policies:
        - S3FullAccessPolicy:
            BucketName: 'cevo-mf-recommender'  
      Events:
        GetProducts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /products
            Method: get
      Environment:
        Variables:
          BEST_MODEL: !Ref BestModel
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./get_products
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ImplicitGetProductsApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Products function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products/"
  ImplicitGetProductsFunction:
    Description: "Get Products Lambda Function ARN"
    Value: !GetAtt ImplicitGetProductsFunction.Arn
  ImplicitGetProductsFunctionIamRole:
    Description: "Implicit IAM Role created for Get Products function"
    Value: !GetAtt ImplicitGetProductsFunctionRole.Arn
